package com.zy.entity;

public class RoletreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.rid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.tid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.rid
     *
     * @return the value of roletree.rid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.rid
     *
     * @param rid the value for roletree.rid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.tid
     *
     * @return the value of roletree.tid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.tid
     *
     * @param tid the value for roletree.tid
     *
     * @mbggenerated Mon Apr 15 15:29:27 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}